<a href="https://colab.research.google.com/github/AlexeyTri/DASH_APP/blob/master/%20PyTorch/TorchTutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [15]:
torch.empty(3)

tensor([0.0000e+00, 0.0000e+00, 3.9236e-44])

In [16]:
torch.rand(2,2)

tensor([[0.9546, 0.4284],
        [0.4856, 0.1949]])

In [17]:
torch.zeros(4)

tensor([0., 0., 0., 0.])

In [18]:
torch.ones(3,3, dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [19]:
x = torch.tensor([2.3,2])

tensor([2.3000, 2.0000])

In [27]:
y = torch.add(x,x)
y.add_(x)
y

tensor([6.2912e-34, 0.0000e+00, 4.7924e-43])

In [38]:
x = torch.rand(4,4)
x

tensor([[0.4288, 0.0104, 0.6931, 0.4201],
        [0.6429, 0.7988, 0.8716, 0.3341],
        [0.5377, 0.2955, 0.1467, 0.8465],
        [0.6959, 0.3830, 0.8805, 0.7140]])

In [39]:
x.view(2,8)

tensor([[0.4288, 0.0104, 0.6931, 0.4201, 0.6429, 0.7988, 0.8716, 0.3341],
        [0.5377, 0.2955, 0.1467, 0.8465, 0.6959, 0.3830, 0.8805, 0.7140]])

In [40]:
x.view(-1, 8)

tensor([[0.4288, 0.0104, 0.6931, 0.4201, 0.6429, 0.7988, 0.8716, 0.3341],
        [0.5377, 0.2955, 0.1467, 0.8465, 0.6959, 0.3830, 0.8805, 0.7140]])

In [42]:
x = torch.ones(6)

In [45]:
y = x.numpy()
y

array([1., 1., 1., 1., 1., 1.], dtype=float32)

In [46]:
x.add_(1)

tensor([2., 2., 2., 2., 2., 2.])

In [47]:
z = torch.from_numpy(y)
z

tensor([2., 2., 2., 2., 2., 2.])

In [48]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z.to('cpu')

In [49]:
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

# Gradient Calculation With Autograd

In [55]:
# requires_grad=True записывает в дифференцирование данный элемент, обязательно в конце цикла выключить его
x = torch.randn(3, requires_grad=True)
# функция должна быть функцией суммы, так как это сумма по всем элементам тензора
y = ((x+2)**2).sum()
# z = y*y*2
# # z = z.mean()
# v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)

In [56]:
# y.backward(torch.ones(y.shape)) - не обязательно, но в скобках указываем размерность тензора градиента
y.backward()

In [57]:
x.grad

tensor([5.7889, 4.8946, 4.8204])

In [76]:
x = torch.randn(3, requires_grad=True)
x.requires_grad_(False)
y = x.detach()

In [82]:
with torch.no_grad():
    y = x + 2

y

tensor([0.4201, 2.6012, 3.1135])

In [89]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights,  lr=0.01)
optimizer.step()
optimizer.zero_grad()

# Backpropagation - Theory With Example